config/routes.rb
Rails.application.routes.draw do

  resources :notifications do
    collection do
      post 'mark_all'
      get 'update_notification'    
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.append do
    namespace :admin do
      resources :stock_items
      resources :reports, :only => [:index] do
        collection do
          get :top_products
          post :top_products
          get :top_cities
          get :daily
          get :sale_performances
          get :returning_customer
          get :traffic_referrer
        end
      end
      resources :notifications
      resources :variants, :only => [:index] do
        member do 
          get :get_info
        end
      end
      resources :store_templates
      resources :sale_performances
      resources :leads 
      resources :leadlists
      resources :comments
      resources :notes
      resources :print_order_addresses
      resources :addresses do
        get :get_addresses
      end
      resources :lead_lists
      resources :products do
        member do
          get :recover
        end
        collection do
          get :search
        end
      end
      resources :sliders do
        resources :slider_images
      end
      resources :orders do
        member do
          post :transfer
          get :accept_transfer
        end

        resources :line_items do
          member do
            put :update_variant
          end
        end
      end
      get "unassigned" => "orders#index"
    end
    namespace :api, defaults: { format: 'json' } do
      resources :shipments, only: [:create, :update] do
        member do
          put :finish
        end
      end
    end
    get "admin/login" => "admin#login"
    get "my-albums" => "users#albums"
    resources :albums do
      member do
        post :set_cover
        post :like
        post :unlike
      end
    end

    resources :photos
    resources :users do
      collection do
        post :update_phone
      end
    end
    get "my-campaigns" => "users#campaigns"
    get "referred-orders" => "users#referred_orders"
    get "withdraw-money" => "users#withdraw_money"
    post "send-withdraw-money" => "users#send_withdraw_money"
    get "withdraw-money/success" => "users#success"

    get "/cung-chup-anh-xinh-rinh-qua-that-da" => "home#about_albums_competition"
  end
  
  
  post "/update_cam_status" => "campaigns#update_status"

  resources :districts
  resources :comments
  resources :campaigns
  resources :pictures 
  resources :notifications do
    collection do
      post 'mark_all'
    end
  end

  Spree::Core::Engine.add_routes do
    
    resources :products do
      collection do
        get :search
        get :search_show
      end
    end
  end

end

app/views/spree/admin/images/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label Spree.t(:filename) %><br>
      <%= f.file_field :attachment %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.label Spree::Variant.model_name.human %><br>
      <%= f.select :viewable_id, @variants, {}, {:class => 'select2 fullwidth'} %>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.hidden_field :alt, :rows => 4, :class => 'fullwidth',:value => @product.name , readonly: true%>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/images/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Images'} %>


<% content_for :page_actions do %>
  <li>
    <%= form_for admin_product_images_path, :html => {:id => "new_product_image", :multipart => true}, :method => "POST" do |f| %>
      <div class="file_upload_btn">
        <input type="file" name="image[attachment][]" id="file_upload" multiple>
        <span class="new_image_text">
          <i class="fa fa-plus"></i>
          HÌNH MỚI
        </span>
      </div>
    <% end %>
  </li>
<% end %>


<div id="images" data-hook></div>

<div id="image_list">
<% unless @product.images.any? || @product.variant_images.any? %>
  <div class="no-objects-found">
    <%= Spree.t(:no_images_found) %>.
  </div>
<% else %>
<%= form_for admin_product_images_path, :html => {:id => "edit_product_image", :multipart => true}, :method => "PUT" do |f| %>
  <input type="hidden" name="image[viewable_id]" value="<%= @product.master.id %>">
  <table class="index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_product_images_url(@product) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <% if @product.has_variants? %>
        <col style="width: 25%">
      <% end %>
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <% if @product.has_variants? %>
          <th><%= Spree::Variant.model_name.human %></th>
        <% end %>
        <th><%= Spree.t(:alt_text) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@product.variant_images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <div class="change_image_<%= image.id %>" style="background: url(<%= image.attachment.url(:mini) %>) no-repeat">
              <input type="file" name="image[attachment]" data-image-id="<%= image.id %>" class="update_image"/>
            </div>
          </td>
          <% if @product.has_variants? %>
            <td><%= options_text_for(image) %></td>
          <% end %>
          <td><%= image.alt %></td>
          <td class="actions">
            <%= link_to_with_icon 'edit', Spree.t(:edit), edit_admin_product_image_url(@product, image), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete image, { :url => admin_product_image_url(@product, image), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<% end %>
</div>
<%= render :partial => 'spree/admin/shared/image_ajax_uploaded.js.erb' %>