config/routes.rb
Rails.application.routes.draw do

  resources :notifications do
    collection do
      post 'mark_all'
      get 'update_notification'    
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.append do
    namespace :admin do
      resources :stock_items
      resources :reports, :only => [:index] do
        collection do
          get :top_products
          post :top_products
          get :top_cities
          get :daily
          get :sale_performances
          get :returning_customer
          get :traffic_referrer
        end
      end
      resources :notifications
      resources :variants, :only => [:index] do
        member do 
          get :get_info
        end
      end
      resources :store_templates
      resources :sale_performances
      resources :leads 
      resources :leadlists
      resources :comments
      resources :notes
      resources :print_order_addresses
      resources :addresses do
        get :get_addresses
      end
      resources :lead_lists
      resources :products do
        member do
          get :recover
        end
        collection do
          get :search
        end
      end
      resources :sliders do
        resources :slider_images
      end
      resources :orders do
        member do
          post :transfer
          get :accept_transfer
        end

        resources :line_items do
          member do
            put :update_variant
          end
        end
      end
      get "unassigned" => "orders#index"
    end
    namespace :api, defaults: { format: 'json' } do
      resources :shipments, only: [:create, :update] do
        member do
          put :finish
        end
      end
    end
    get "admin/login" => "admin#login"
    get "my-albums" => "users#albums"
    resources :albums do
      member do
        post :set_cover
        post :like
        post :unlike
      end
    end

    resources :photos
    resources :users do
      collection do
        post :update_phone
      end
    end
    get "my-campaigns" => "users#campaigns"
    get "referred-orders" => "users#referred_orders"
    get "withdraw-money" => "users#withdraw_money"
    post "send-withdraw-money" => "users#send_withdraw_money"
    get "withdraw-money/success" => "users#success"

    get "/cung-chup-anh-xinh-rinh-qua-that-da" => "home#about_albums_competition"
  end
  
  
  post "/update_cam_status" => "campaigns#update_status"

  resources :districts
  resources :comments
  resources :campaigns
  resources :pictures 
  resources :notifications do
    collection do
      post 'mark_all'
    end
  end

  Spree::Core::Engine.add_routes do
    
    resources :products do
      collection do
        get :search
        get :search_show
      end
    end
  end

end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
module Spree
  module Admin
    module Orders
      CustomerDetailsController.class_eval do
        def update
          params["order"]["bill_address_attributes"]["phone"].delete(' ') if params["order"]["bill_address_attributes"]["phone"].present?
          @lead = Spree::Lead.find_by(phone: params[:order][:bill_address_attributes][:phone])
          if @lead.present?
            @order.lead_id = @lead.id
          else
            @lead = Spree::Lead.create(user_id: spree_current_user.id, phone: params[:order][:bill_address_attributes][:phone], name: params[:order][:bill_address_attributes][:firstname], state_id: params[:order][:bill_address_attributes][:state_id], district_id: params[:order][:bill_address_attributes][:district_id], )
            @order.update(lead_id: @lead.id )
          end
          products = @order.line_items.map{|l| l.variant.product } 
          @lead.products << products
          if @order.update(order_params)
            if params[:guest_checkout] == "false"
              @order.associate_user!(Spree.user_class.find(params[:user_id]), @order.email.blank?)
            else 
              @order ||= current_order
              if try_spree_current_user && @order
                @order.associate_user!(try_spree_current_user) if @order.user.blank? || @order.email.blank?
              end
            end
            while @order.next; end
            @order.refresh_shipment_rates
            flash[:success] = Spree.t('customer_details_updated')
            p "=============+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
           
            p @order
            redirect_to edit_admin_order_path(@order)
          else
            render :action => :edit
          end

        end

        private
          def order_params
            params.require(:order).permit(
              :email, :user_id,
              :use_billing,
              :bill_address_attributes => permitted_address_attributes,
              :ship_address_attributes => permitted_address_attributes,
            )
          end
      end
    end
  end
end

app/views/spree/admin/orders/_form.html.erb
 <div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
  <% end %>

    <%= render :partial => "spree/admin/orders/shipment", :locals => { :order => order, :shipment => @order.shipments.first } if @order.shipments.present? %>
    <div class="col-md-6">
      <%= form_for @order, :url => admin_order_customer_url(@order) do |f| %>
        <%= render 'spree/admin/orders/customer_details/form', :f => f %>
      <% end %>
    </div>
    <p class="clearfix"></p>
    <br/>
    <%= render partial: 'spree/admin/orders/add_product' if @order.shipment_state != 'shipped' && can?(:update, @order) %>
    <%= render :partial => "spree/admin/orders/line_items", :locals => { :order => order } %>


  <%#= render :partial => "spree/admin/orders/adjustments", :locals => {
        :adjustments => @order.line_item_adjustments,
        :order => order,
        :title => Spree.t(:line_item_adjustments)
   } %>
  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
        :adjustments => @order.shipment_adjustments,
        :order => order,
        :title => Spree.t(:shipment_adjustments)
   } %>
  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
        :adjustments => @order.adjustments,
        :order => order,
        :title => Spree.t(:order_adjustments)
   } %>

  <% if order.line_items.exists? %>
    <fieldset class="no-border-bottom" id="order-total" data-hook="order_details_total">
      <legend><%= Spree.t(:order_total) %></legend>
      <span class="order-total"><%= order.display_total %></span>
    </fieldset>
  <% end %>

  <%= javascript_tag do -%>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
            shipments.push(<%== shipment.as_json(:root => false, :only => [:id, :tracking, :number, :state, :stock_location_id], :include => [:inventory_units, :stock_location]).to_json %>);
    <% end %>
    <%= render :partial => 'spree/admin/shared/update_order_state', :handlers => [:js] %>
  <% end -%>
<!--   <%= form_for order, :url=>spree.admin_order_path(order) do |form| %>
    <%= form.label :note %>
    <%= form.text_area :note, cols: 60, rows: 5 %>
    <%= form.submit :save %>
  <% end %> -->
</div>

app/views/spree/admin/orders/_line_item.html.erb
<tr id="<%= spree_dom_id(f.object) %>" data-hook="admin_order_form_line_item_row" class="<%= cycle('odd', 'even')%>">
  <td><%=f.object.variant.product.name%> <%= "(#{f.object.variant.options_text})" unless f.object.variant.option_values.empty? %></td>
  <td class="price align-center"><%= f.object.single_money %></td>
  <td class="qty"><%= f.number_field :quantity, :min => 0, :class => "qty" %></td>
  <td class="total align-center"><%= f.object.display_amount %></td>
  <td data-hook="admin_order_form_line_item_actions" class="actions">
    <%= link_to_delete f.object, {:url => admin_order_line_item_url(@order.number, f.object), :no_text => true} %>
  </td>
</tr>

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
  <table class="line-items index" data-hook="line-items">
    <colgroup>
      <col style="width: 10%;" />
      <col style="width: 20%;" />
      <col style="width: 20%;" />
      <col style="width: 15%;" />
    </colgroup>

    <thead>
      <th colspan="2"><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:quantity) %></th>
      <th><%= Spree.t(:total_price) %></th>
      <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions">&nbsp;</th>
    </thead>

    <tbody>
      <% order.line_items.each do |item| %>
        <tr class="line-item" id="line-item-<%= item.id %>">
          <td class="line-item-image"><%= mini_image(item.variant) %></td>
          <td class="line-item-name">
            <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
          </td>
          <td class="line-item-price align-center"><%= item.single_money.to_html %></td>
          <td class="line-item-qty-show align-center">
            <%= item.quantity %>
          </td>
          <td class="line-item-qty-edit none-display">
            <%= number_field_tag :quantity, item.quantity, :min => 0, :class => "line_item_quantity", :size => 5 %>
          </td>
          <td class="line-item-total align-center"><%= line_item_shipment_price(item, item.quantity) %></td>
          <td class="cart-line-item-delete actions" data-hook="cart_line_item_delete">
            <% if can? :update, item %>
              <%= link_to '', 'javascript:void(0)', :class => 'save-line-item fa fa-ok no-text with-tip', :data => { 'line-item-id' => item.id, :action => 'save'}, :title => Spree.t('actions.save'), :style => 'display: none' %>
              <%= link_to '', 'javascript:void(0)', :class => 'cancel-line-item fa fa-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel'), :style => 'display: none' %>
              <%= link_to '', 'javascript:void(0)', :class => 'edit-line-item fa fa-edit no-text with-tip', :data => {:action => 'edit'}, :title => Spree.t('edit') %>
              <%= link_to '', 'javascript:void(0)', :class => 'delete-line-item fa fa-trash no-text with-tip', :data => { 'line-item-id' => item.id, :action => 'remove'}, :title => Spree.t('delete') %>
              <!-- Single button -->
              
              <div class="btn-group select-color" role="group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <%= Spree.t(:select_color) %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <% item.variant.product.variants.each do |variant| %>
                  <li><%= link_to variant.options_text, '#', :class => 'select-color-line-item', :data => { 'line-item-id' => item.id, 'action-url' => update_variant_admin_order_line_item_path(order, item), 'variant-id' => variant.id} %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<h5 class="text-center title-adjustments-order"><%= Spree.t(:adjustments) %></h5>
<%= form_for Spree::Adjustment.new, :url => admin_order_adjustments_path(@order.number), :method => :post do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'spree/admin/adjustments/form', :locals => { :f => f } %>

    <div class="filter-actions actions btn-adjustment-order" data-hook="buttons">
      <%= button Spree.t(:continue), 'arrow-right' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_order_adjustments_url(@order), :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/orders/_list_order_admin.html.erb
<%= paginate @orders %>
<% if @orders.any? %>
<table class="index responsive" id="listing_orders" data-hook>
  <colgroup>
    <col style="width: 8%;">
    <col style="width: 8%;">
    <col style="width: 8%;">
    <col style="width: 8%;">
    <% if Spree::Order.checkout_step_names.include?(:delivery) %>
    <col style="width: 10%;">
    <% end %>
    <col style="width: 8%;">
    <col style="width: 12%;">
    <col style="width: 9%;">
    <col style="width: 8%;">
    <col style="width: 13%;">
  </colgroup>
  <thead>
    <tr data-hook="admin_orders_index_headers">
      <% if @show_only_completed %>
      <% if @show_only_paid %>
      <th><%= sort_link @search, :updated_at,   I18n.t(:paid_at, :scope => 'activerecord.attributes.spree/order') %>
      </th>
      <% else %>
      <th>
        <%= sort_link @search, :completed_at,   I18n.t(:completed_at, :scope => 'activerecord.attributes.spree/order') %>
      </th>
      <% end %>
      <% else %>
      <th>
        <%= sort_link @search, :created_at,     I18n.t(:created_at, :scope => 'activerecord.attributes.spree/order') %>
      </th>
      <% end %>
      <th><%= sort_link @search, :number,           I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %>
      </th>
      <th><%= sort_link @search, :state,            I18n.t(:state, :scope => 'activerecord.attributes.spree/order') %>
      </th>
      <th>
        <%= sort_link @search, :payment_state,    I18n.t(:payment_state, :scope => 'activerecord.attributes.spree/order') %>
      </th>

      <th>
        <%= sort_link @search, :shipment_state, I18n.t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %>
      </th>

      <th><%= sort_link @search, :email,            I18n.t(:full_name, :scope =>'spree') %></th>
      <th><%= sort_link @search, :phone,            I18n.t(:phone, :scope =>'spree') %></th>
      <th><%= sort_link @search, :total,            I18n.t(:total, :scope => 'activerecord.attributes.spree/order') %>
      </th>
      <th><%= Spree.t(:note) %></th>
      <th><%= Spree.t(:website) %></th>
     
      <th><%= Spree.t(:device) %></th>
      <th><%= Spree.t(:source) %></th>

      <th><%= Spree.t(:processing) %></th>
      <th data-hook="admin_orders_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
    <tr data-hook="admin_orders_index_rows"
      class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %> <%= "fake-order" if order.is_risky? %>">
      <td class="align-center">
        <%= l (@show_only_completed ? (@show_only_paid ? order.updated_at : order.completed_at) : order.created_at).to_date %>
      </td>
      <td class="align-center"><%= link_to order.number, edit_admin_order_path(order), :target => "_blank" %></td>
      <td class="align-center"><span
          class="state <%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span></td>
      <td class="align-center"><span
          class="state <%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></span>
      </td>

      <td class="align-center"><span class="state <%= order.shipment_state_new %>">
          <%= Spree.t("shipment_states.#{order.shipment_state_new}") %>

        </span></td>

      <td><%= order.billing_address.firstname if order.billing_address.present? %></td>
      <% if order.billing_address.present? %>
      <td>
        <%= order.approver_id.present? ? order.billing_address.formatted_phone : order.billing_address.formatted_phone[0..6] + "xxx" %>
      </td>
      <% end %>
      <td class="align-center"><%= order.approver_id.present? ? order.display_total.to_html : "xxx" %></td>
      <td id="order-<%= order.id %>">
        <% order.notes.each do |note| %>
        <div><%= "(#{note.created_at.strftime('%d/%m %H:%M')})  -  #{note.content}" %></div>
        <% end %>
      </td>
      <td>
        <%= order.store_name %>
      </td>
      
      <td>
        <%= order.device.present? ? order.device : "" %>
      </td>
      <td>
        <%= order.source %>
      </td>
 
      <td class="align-center"><%= order.approver.present? ? order.approver.nickname : "" %></td>
      <td class='actions align-center' data-hook="admin_orders_index_row_actions">
        <%= link_to "", "##{order.number}-notes", :title => Spree.t(:note), :no_text => true, :class => "fa fa-comment icon_link with-tip no-text notes" %>
        <div style="display:none">
          <div id="<%= order.number%>-notes" style="width: 600px; height: 300px;">
            <%= form_for Spree::Note.new(), :url=>admin_notes_path(), :remote => true, :class => "new-note-form" do |f| %>
            <%= f.select :note_template_id, NoteTemplates.all.collect {|n| [n.name, n.id]}, {}, :id => "", :class => "note_select form-control"%>
            <%= f.text_field :content, :class => "form-control" %>
            <%= f.hidden_field :notable_id, :value => order.id %>
            <%= f.hidden_field :notable_type, :value => "Spree::Order" %>
            <%= f.submit Spree.t(:note), :class => "button create-note", :style => "margin-top: 5px; float:right;" %>
            <br />
            <div class="note-list">
              <% order.notes.each do |note| %>
              <div><%= "(#{note.created_at.strftime('%d/%m %H:%M')})  -  #{note.content}" %></div>
              <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<div class="alpha twelve columns no-objects-found">
  <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/order')) %>,
      <%=link_to Spree.t(:add_one), new_admin_order_url(:order => {:bill_address_attributes => {:firstname => "donghox", :phone => "0908482804"}})%>  
</div>
<% end %>

<%= paginate @orders %>

app/views/spree/admin/orders/_note.html.erb
<div style="display:none">
	<div id="notes">
		<% notes.each do |note| %>
			<div><%= "#{note.created_at}: note.content" %></div>
		<% end %>
	</div>
</div>

app/views/spree/admin/orders/_shipment_manifest.html.erb
<% shipment.manifest.each do |item| %>
  <tr class="stock-item" data-item-quantity="<%= item.quantity %>">
    <td class="item-image">
      <%= mini_image(item.variant) %>
    </td>
    <td class="item-name">
      <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
      <% if item.variant.sku.present? %>
        <strong><%= Spree.t(:sku) %>:</strong> <%= item.variant.sku %>
      <% end %>
    </td>
    <td class="item-price align-center"><%= item.line_item.single_money.to_html %></td>
    <td class="item-qty-show align-center">
        <% item.states.each do |state,count| %>
          <%= count %> x <%= Spree.t(state).downcase %>
        <% end %>
    </td>
    <% unless shipment.shipped? %>
      <td class="item-qty-edit hidden">
        <%= number_field_tag :quantity, item.quantity, :min => 0, :class => "line_item_quantity", :size => 5 %>
      </td>
    <% end %>
    <td class="item-total align-center"><%= line_item_shipment_price(item.line_item, item.quantity) %></td>
    <% unless shipment.shipped? %>
      <td class="cart-item-delete actions" data-hook="cart_item_delete">
        <% if can? :update, item %>
          <%= link_to '', '#', :class => 'save-item fa fa-ok no-text with-tip', :data => {'shipment-number' => shipment.number, 'variant-id' => item.variant.id, :action => 'save'}, :title => Spree.t('actions.save'), :style => 'display: none' %>
          <%= link_to '', '#', :class => 'cancel-item fa fa-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel'), :style => 'display: none' %>
          <%= link_to '', '#', :class => 'edit-item fa fa-edit no-text with-tip', :data => {:action => 'edit'}, :title => Spree.t('edit') %>

          <%= link_to '', '#', :class => 'delete-item fa fa-trash no-text with-tip', :data => { 'shipment-number' => shipment.number, 'variant-id' => item.variant.id, :action => 'remove'}, :title => Spree.t('delete') %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/spree/admin/orders/_transfer_form.html.erb
<%= form_for @order, :url => transfer_admin_order_path(@order), :html => {:id => "transfer-form", :method => "POST"} do |f| %>
	<ul>
	<% @sales.each do |sale| %>
		<li><%= radio_button("order", "authorized_approver_id", sale.id.to_s) %> <%= sale.nickname %><li>
	<% end %>
	</ul>
	<%= f.submit "Transfer" %>
<% end %>

app/views/spree/admin/orders/edit.html.erb
<% is_admin = spree_current_user.has_spree_role?('admin') %>
<% content_for :page_actions do %>
  <li>
  <% if @order.is_risky? %>
    <%= link_to Spree.t(:fake_order), "#", :class => "fa fa-warning fake-order icon_link with-tip no-text button" %>
  <% end %>
  <%= render partial: "spree/admin/shared/notes", locals: { target: @order, note_type: "Spree::Order" } %>
  </li>
  <% if @order.approver_id.present? &&  (@order.approver_id == spree_current_user.id || is_admin) %>
    <li><%= button_link_to Spree.t(:transfer), "#transfer-form", icon: 'email', :id => "transfer-order" %></li>
    <div style="display:none">
      <%= render "transfer_form" %>
    </div>
  <% end %>
  <% if @order.authorized_approver_id.present? &&  @order.authorized_approver_id == spree_current_user.id %>
    <li><%= button_link_to Spree.t(:accept), accept_transfer_admin_order_path, icon: 'email' %></li>
  <% end %>
  <% if can?(:fire, @order) %>
    <li><%= event_links %></li>
  <% end %>
  <% if can?(:resend, @order) %>
    <li><%= button_link_to Spree.t(:resend), resend_admin_order_url(@order), method: :post, icon: 'email' %></li>
  <% end %>
  <% if can?(:admin, Spree::Order) %>
    <li><%= button_link_to Spree.t(:back_to_orders_list), admin_orders_path, icon: 'arrow-left' %></li>
  <% end %>

<% end %>

<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: 'Order Details' } %>

<div data-hook="admin_order_edit_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>
  <% if @order.approver.present? && @order.approver.id != spree_current_user.id %>
    <div class="alert alert-danger" role="alert"><%= Spree.t(:order_processing_by) + " #{@order.approver.nickname}" %></div>
  <% end %>
</div>

<% if @order.payments.exists? && @order.considered_risky? %>
  <%= render 'spree/admin/orders/risk_analysis', latest_payment: @order.payments.order("created_at DESC").first %>
<% end %>

<%#= render partial: 'add_product' if @order.shipment_state != 'shipped' && can?(:update, @order) %>

<% if @order.line_items.empty? %>
  <div class="no-objects-found">
    <%= Spree.t(:your_order_is_empty_add_product)%>
  </div>
<% end %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render partial: 'form', locals: { order: @order } %>
  </div>
</div>
<% if @orders.present? && @orders.any? %>
  <fieldset class="no-border-bottom" id="order-history" >
    <legend><%= Spree.t(:order_history) %></legend>

  </fieldset>
  <table class="index responsive" id="listing_orders" data-hook>
    <colgroup>
       <col style="width: 8%;">
       <col style="width: 8%;">
       <col style="width: 8%;">
       <col style="width: 8%;">
       <% if Spree::Order.checkout_step_names.include?(:delivery) %>
         <col style="width: 10%;">
       <% end %>
       <col style="width: 8%;">
       <col style="width: 12%;">
       <col style="width: 8%;">
       <col style="width: 8%;">
       <col style="width: 20%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_orders_index_headers">

        <th><%= I18n.t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>

        <th><%= I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= I18n.t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= I18n.t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>

        <th><%= I18n.t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>

        <th><%= I18n.t(:full_name, :scope =>'spree') %></th>
        <th><%= I18n.t(:phone, :scope =>'spree') %></th>
        <th><%= I18n.t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= Spree.t(:note) %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td class="align-center"><%= l (@show_only_completed ? (@show_only_paid ? order.updated_at : order.completed_at) : order.created_at).to_date %></td>
        <td class="align-center"><%= link_to order.number, edit_admin_order_path(order), target: "_blank" %></td>
        <td class="align-center"><span class="state <%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span></td>
        <td class="align-center"><span class="state <%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></span></td>

        <td class="align-center"><span class="state <%= order.shipment_state_new %>">
          <%= Spree.t("shipment_states.#{order.shipment_state_new}") %>

        </span></td>

        <td><%= link_to order.billing_address.firstname, admin_order_customer_url(order) if order.billing_address.present? %></td>
        <td><%= order.billing_address.phone if order.billing_address.present? %></td>
        <td class="align-center"><%= order.display_total.to_html %></td>
        <td id="order-<%= order.id %>">
          <% order.notes.each do |note| %>
            <div><%= "(#{note.created_at.strftime('%d/%m %H:%M')})  -  #{note.content}" %></div>
          <% end %>
        </td>
        <td class='actions align-center' data-hook="admin_orders_index_row_actions">
          <%= link_to "", "##{order.number}-notes", :title => Spree.t(:note), :no_text => true, :class => "fa fa-edit icon_link with-tip no-text notes" %>
          <div style="display:none">
            <div id="<%= order.number%>-notes" style="width: 600px; height: 300px;">
              <%= form_for Spree::Note.new(), :url=>admin_notes_path(), :remote => true, :class => "new-note-form" do |f| %>
                <%= f.text_field :content, :style => "width: 400px;" %>
                <%= f.hidden_field :notable_id, :value => order.id %>
                <%= f.hidden_field :notable_type, :value => "Spree::Order" %>
                <%= f.submit Spree.t(:note), :class => "button create-note" %>

              <br/>
              <div class="note-list">
              <% order.notes.each do |note| %>
                <div><%= "(#{note.created_at.strftime('%d/%m %H:%M')})  -  #{note.content}" %></div>
              <% end %>
              </end>
              <% end %>
            </div>
          </div>
          </div>
          <%= check_box_tag "print_orders[]", order.id, false, :class => "print_orders" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/index.js.erb
$("#listing_orders").html("<%= escape_javascript(render partial: 'list_order_admin', locals: { orders: @orders } ) %>");