config/routes.rb
Rails.application.routes.draw do

  resources :notifications do
    collection do
      post 'mark_all'
      get 'update_notification'    
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.append do
    namespace :admin do
      resources :stock_items
      resources :reports, :only => [:index] do
        collection do
          get :top_products
          post :top_products
          get :top_cities
          get :daily
          get :sale_performances
          get :returning_customer
          get :traffic_referrer
        end
      end
      resources :notifications
      resources :variants, :only => [:index] do
        member do 
          get :get_info
        end
      end
      resources :store_templates
      resources :sale_performances
      resources :leads 
      resources :leadlists
      resources :comments
      resources :notes
      resources :print_order_addresses
      resources :addresses do
        get :get_addresses
      end
      resources :lead_lists
      resources :products do
        member do
          get :recover
        end
        collection do
          get :search
        end
      end
      resources :sliders do
        resources :slider_images
      end
      resources :orders do
        member do
          post :transfer
          get :accept_transfer
        end

        resources :line_items do
          member do
            put :update_variant
          end
        end
      end
      get "unassigned" => "orders#index"
    end
    namespace :api, defaults: { format: 'json' } do
      resources :shipments, only: [:create, :update] do
        member do
          put :finish
        end
      end
    end
    get "admin/login" => "admin#login"
    get "my-albums" => "users#albums"
    resources :albums do
      member do
        post :set_cover
        post :like
        post :unlike
      end
    end

    resources :photos
    resources :users do
      collection do
        post :update_phone
      end
    end
    get "my-campaigns" => "users#campaigns"
    get "referred-orders" => "users#referred_orders"
    get "withdraw-money" => "users#withdraw_money"
    post "send-withdraw-money" => "users#send_withdraw_money"
    get "withdraw-money/success" => "users#success"

    get "/cung-chup-anh-xinh-rinh-qua-that-da" => "home#about_albums_competition"
  end
  
  
  post "/update_cam_status" => "campaigns#update_status"

  resources :districts
  resources :comments
  resources :campaigns
  resources :pictures 
  resources :notifications do
    collection do
      post 'mark_all'
    end
  end

  Spree::Core::Engine.add_routes do
    
    resources :products do
      collection do
        get :search
        get :search_show
      end
    end
  end

end

app/views/spree/admin/variants/_edit_fields.html.erb
<h3><%= Spree.t(:volume_prices) %></h3>
<table class="index">
  <thead>
    <tr>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:discount_type) %></th>
      <th><%= Spree.t(:range) %></th>
      <th>Giá trị đầu</th>
      <th>Giá trị cuối</th>
      <th><%= Spree.t(:amount) %></th>
      <th><%= Spree.t(:position) %></th>
      <th><%= Spree.t(:action) %></th>
    </tr>
  </thead>
  <tbody id="volume_prices">
    <%= f.fields_for :volume_prices do |vp_form| %>
      <%= render 'volume_price_fields', :f => vp_form %>
    <% end %>
  </tbody>
</table>
<%#= link_to_add_fields Spree.t(:add_volume_price), "tbody#volume_prices" %>
<%= link_to_add_fields Spree.t(:add_volume_price), "tbody#volume_prices", {:class => 'new_volume_price_row'} %>
<br/><br/>

app/views/spree/admin/variants/_volume_price_fields.html.erb
<tr class="volume_price fields">
  <td>
    <%= error_message_on(f.object, :range) %>
    <%= f.number_field :range_start %>
  </td>
  <td>
    <%= error_message_on(f.object, :range) %>
    <%= f.number_field :range_end %>
  </td>
  <td class="hide">
    <%= error_message_on(f.object, :discount_type) %>
    <%= f.select :discount_type, options_for_select( [["#{Spree.t(:total_price)}",'price'],["#{Spree.t(:percent_discount)}",'percent'],["#{Spree.t(:price_discount)}",'dollar']], f.object.discount_type ), { inlcude_blank: true }, class: 'btn btn-primary' %>
  </td>
  <td class="hide">
    <%= error_message_on(f.object, :name) %>
    <%= f.text_field :name, :size => 10, class: "name" %>
  </td>
  <td class="hide">
    <%= error_message_on(f.object, :range) %>
    <%= f.text_field :range, :size => 10, class: "range" %>
  </td>
  <td>
    <%= error_message_on(f.object, :amount) %>
    <%= f.text_field :amount, :size => 10 %>
  </td>
  <td class="hide">
    <%= error_message_on(f.object, :position) %>
    <%= f.text_field :position, :size => 3 %>
  </td>
  <td class="actions">
    <%= link_to_remove_fields '', f, class: 'no-text' %>
  </td>
</tr>

app/views/spree/admin/variants/volume_prices.html.erb
<%= render 'spree/admin/shared/product_sub_menu' %>
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: Spree.t(:volume_pricing) } %>
<%= render "spree/shared/error_messages", :target => @variant %>

<%= form_for(@variant, :url => admin_product_variant_path(@product, @variant), :html => { :method => :put }) do |f| %>
  <h3><%= Spree.t(:volume_prices) %></h3>
  <table class="index">
    <thead>
      <tr>
        <th>Giá trị đầu</th>
        <th>Giá trị cuối</th>
        <th class="hide"><%= Spree.t(:discount_type) %></th>
        <th class="hide"><%= Spree.t(:name) %></th>
        
        <th class="hide"><%= Spree.t(:range) %></th>
        <th><%= Spree.t(:amount) %></th>
        <th class="hide"><%= Spree.t(:position) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody id="volume_prices">
      <%= f.fields_for :volume_prices do |vp_form| %>
        <%= render 'volume_price_fields', :f => vp_form %>
      <% end %>
    </tbody>
  </table>
  <%= link_to_add_fields Spree.t(:add_volume_price), "tbody#volume_prices", {:class => 'new_volume_price_row'} %>
  <br/><br/>

  <%= render 'spree/admin/shared/edit_resource_links' %>
<% end %>

<script>
$("body").on("keyup", ".first-value, .last-value", function(e){
    $element = $(e.target)
    $tr_tag = $element.closest('.volume_price')
    $des_td = $tr_tag.find('.range')
    first_value = $tr_tag.find('.first-value').val()
    last_value =  $tr_tag.find('.last-value').val()
    $des_td.val("(" + first_value + ".." + last_value + ")");
});

$("body").on("keyup", ".first-value, .last-value", function(e){
    $(this).parent().children('td:nth-child(4)').val("(" + $(".first-value").val() + ".." + $(".last-value").val() + ")");
    $element = $(e.target)
    $tr_tag = $element.closest('.volume_price')
    $des_td = $tr_tag.find('.name')
    first_value = $tr_tag.find('.first-value').val()
    last_value =  $tr_tag.find('.last-value').val()
    $des_td.val(first_value + "-" + last_value);
});


</script>