config/routes.rb
Rails.application.routes.draw do

  resources :notifications do
    collection do
      post 'mark_all'
      get 'update_notification'    
    end
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.append do
    namespace :admin do
      resources :stock_items
      resources :reports, :only => [:index] do
        collection do
          get :top_products
          post :top_products
          get :top_cities
          get :daily
          get :sale_performances
          get :returning_customer
          get :traffic_referrer
        end
      end
      resources :notifications
      resources :variants, :only => [:index] do
        member do 
          get :get_info
        end
      end
      resources :store_templates
      resources :sale_performances
      resources :leads 
      resources :leadlists
      resources :comments
      resources :notes
      resources :print_order_addresses
      resources :addresses do
        get :get_addresses
      end
      resources :lead_lists
      resources :products do
        member do
          get :recover
        end
        collection do
          get :search
        end
      end
      resources :sliders do
        resources :slider_images
      end
      resources :orders do
        member do
          post :transfer
          get :accept_transfer
        end

        resources :line_items do
          member do
            put :update_variant
          end
        end
      end
      get "unassigned" => "orders#index"
    end
    namespace :api, defaults: { format: 'json' } do
      resources :shipments, only: [:create, :update] do
        member do
          put :finish
        end
      end
    end
    get "admin/login" => "admin#login"
    get "my-albums" => "users#albums"
    resources :albums do
      member do
        post :set_cover
        post :like
        post :unlike
      end
    end

    resources :photos
    resources :users do
      collection do
        post :update_phone
      end
    end
    get "my-campaigns" => "users#campaigns"
    get "referred-orders" => "users#referred_orders"
    get "withdraw-money" => "users#withdraw_money"
    post "send-withdraw-money" => "users#send_withdraw_money"
    get "withdraw-money/success" => "users#success"

    get "/cung-chup-anh-xinh-rinh-qua-that-da" => "home#about_albums_competition"
  end
  
  
  post "/update_cam_status" => "campaigns#update_status"

  resources :districts
  resources :comments
  resources :campaigns
  resources :pictures 
  resources :notifications do
    collection do
      post 'mark_all'
    end
  end

  Spree::Core::Engine.add_routes do
    
    resources :products do
      collection do
        get :search
        get :search_show
      end
    end
  end

end

app/models/spree/lead.rb
class Spree::Lead < Spree::Base
    attr_accessor :email
    belongs_to :user
    has_many :notes, as: :notable
    has_many :orders, :dependent => :destroy
    belongs_to :lead_list, :dependent => :destroy
    belongs_to :state, class_name: 'Spree::State'
    belongs_to :district, class_name: 'Spree::District'
    has_and_belongs_to_many :products, join_table: 'leads_products'
    has_many :pictures
    validates_format_of :phone, :with =>  /\d[0-9]\)*\z/ , :message => "Only positive number without spaces are allowed"

    def images=(files = [])
        files.each do |f|
            pictures.create(image: f)
        end
    end
    # has_attached_file :image
    # validates_attachment :pictures,
                    #  content_type: { content_type: /\Aimage\/.*\z/ },
                    #  size: { less_than: 1.megabyte }
    # after_update :add_to_order

    # private
    # def add_to_order
    #   order = Spree::Order.find_by_number(self.order_number)
    #   order.update_attribute(:lead_id, self.id) if order.present?
    # end
end

app/controllers/spree/admin/leads_controller.rb
module Spree
	module Admin
    class LeadsController < ResourceController
      def index   
        params[:q] ||= {}
        @show_only_unprocessed = params[:show_only_unprocessed] == '1'
        if @show_only_unprocessed
          params[:q][:approver_id_null] = '1'
        end
        params[:q][:completed_at_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
        @show_only_completed = params[:q][:completed_at_not_null] == '1'
        params[:q][:approver_id_eq] ||= spree_current_user.id.to_s if @show_only_unprocessed && spree_current_user.has_spree_role?('sales_rep')
        @show_only_my_orders = params[:q][:approver_id_eq] == spree_current_user.id.to_s
        params[:q].delete(:approver_id_eq) if params[:q][:approver_id_eq] == '0'
        params[:q][:s] ||= @show_only_completed ? 'completed_at desc' : 'created_at desc'
                 
        @lead= Lead.new
    		respond_with(@collection) do |format|
          format.html
          format.js
          format.json { render :json => @collection }
        end
        
      end
      
      def create
        if params[:lead][:phone].present?
          @lead = Lead.new(lead_params)
          if @lead.fb_url.present?
            fb_name = @lead.fb_url.split('/').last
            @lead.fb_name = fb_name.gsub(".","")
          end
          user = User.find_by_phone(params[:lead][:phone])
          @lead.save
          if params[:variant_ids].present?
            products = Product.joins("RIGHT JOIN spree_variants  ON spree_products.id = spree_variants.product_id").where(:spree_variants => {id: params[:variant_ids]}).distinct(:id)
            @lead.products << products
          end
          if user.present?
            @lead.user_id = user.id
          end
          if params[:note].present?
            note = Note.create(content: params[:note], notable_id: @lead.id.to_s, notable_type: "Spree::Lead", lead_id: @lead.id)
          end
          @lead.save
          if params[:images].present?
            params[:images].each do |file|
              @lead.pictures.create(image: file)
            end
          end
          redirect_to admin_leads_path
        else
          flash.now[:error] = Spree.t("lead.product_email_cannot_be_blank")
          render :new
        end
      end

      def edit
        @lead = Lead.find(params[:id])
      end

      def update
        
        @lead.products.delete_all
        if params[:variant_ids].present?
          products = Product.joins("RIGHT JOIN spree_variants  ON spree_products.id = spree_variants.product_id").where(:spree_variants => {id: params[:variant_ids]}).distinct(:id)
          @lead.products << products
        end
        user = User.find_by_phone(params[:lead][:phone])
        @lead.user_id = user.id if user.present?
        @lead = Lead.find(params[:id])
        @lead.save
        @lead.update(lead_params)
        if params[:images].present?
        params[:images].each do |file|
          @lead.pictures.create(image: file)
        end
        end
        if params[:note].present?
          note = Note.create(content: params[:note], notable_id: @lead.id.to_s, notable_type: "Spree::Lead", lead_id: @lead.id)
        end
        redirect_to edit_admin_lead_path(@lead)	
      end

    	protected

      def collection
        return @collection if @collection.present?
        @search = Lead.ransack(params[:q])  
        params[:q] ||= {}
        params[:q][:s] ||= "created_at desc"
        if request.xhr? && params[:q].present? && false
          @collection = Lead.includes(:user,:product)
                            .where("spree_users.email #{LIKE} :search",
                                  { :search => "#{params[:q].strip}%" })
                            .limit(params[:limit] || 100)
        else
          
          # @search = Spree::Lead.ransack(name_or_phone_cont: params[:search])
          @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_products_per_page])
        end
      end
      

      def lead_params
        params.require(:lead).permit(:name, :phone, :user_id, :fb_post_id, :fb_url, :state_id, :district_id, :major, :zalo, :lead_list_id,:website, :company,  pictures_attributes: [ :_destroy, :id, :image] )
      end

    end

  end
end

app/views/spree/admin/leads/_form.html.erb
<%= form_for [:admin, @lead], :html => { :multipart => true } do |f| %>
  <fieldset>
    <legend align="center"><%= @lead.new_record? ? "New Lead" : "Edit Lead" %></legend>
    <div id="form-lead">
    <div class="col-md-6">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name, :class => 'fullwidth modal-pad', placeholder: Spree.t(:name_not_nil), :onkeyup => "onChange()" %>
    <% end %>

    <%= f.field_container :phone do %>
      <%= f.label :phone, Spree.t(:phone) %>
      <%= f.text_field :phone, :class => 'fullwidth modal-pad', placeholder: Spree.t(:phone_not_nil), :onkeyup => "onChange()" %>
      <span id="spnPhoneStatus"></span>
    <% end %>
    <%= f.field_container :website do %>
      <%= f.label :website, Spree.t(:website) %>
      <%= f.text_field :website, :class => 'fullwidth modal-pad' %>
    <% end %>
    <%= f.field_container :company do %>
      <%= f.label :company, Spree.t(:company) %>
      <%= f.text_field :company, :class => 'fullwidth modal-pad' %>
    <% end %>
   
    <%= f.field_container :zalo do %>
      <%= f.label :zalo, Spree.t(:zalo) %>
      <%= f.text_field :zalo, :class => 'fullwidth modal-pad ' %>
    <% end %>

    <%= f.field_container :fb_url do %>
      <%= f.label :fb_url, Spree.t(:fb_url) %>
      <%= f.text_field :fb_url, :class => 'fullwidth modal-pad' %>
    <% end %>

    <%= f.field_container :major do %>
      <%= f.label :major, Spree.t(:major) %>
      <%= f.text_field :major, :class => 'fullwidth modal-pad' %>
    <% end %>
    </div>
    <div class="col-md-6">
    <% country = Spree::Country.find_by_iso("VN") %>
    <%= label_tag :note, Spree.t(:note) %>
    <%= text_area_tag :note,'' ,:class => 'fullwidth', :style => "resize: none" %>
    <%= f.field_container :state_id do %>
      <%= f.label :city, Spree.t(:city), :class => "fullwidth" %>
      <%= f.collection_select :state_id, country.states.sort, :id, :name, {:include_blank => true}, {:id => 'order_bill_address_attributes_state_id', :class => 'select2 fullwidth', :style => "display: #{country.states.empty? ? 'none' : 'block' };", :disabled => country.states.empty?} %>
    <% end %>
  
    <% f.object.state = country.states.first unless f.object.state.present? %>
    <%= f.field_container :state_id do %>
      <%= f.label :district, Spree.t(:district), :class => "fullwidth" %>
      <%= f.collection_select :district_id, f.object.state.districts.sort, :id, :name, {:include_blank => true}, {:id => 'order_bill_address_attributes_district_id',:class => 'select2 fullwidth', :style => "display: #{f.object.state.districts.empty? ? 'none' : 'block' };", :disabled => f.object.state.districts.empty?} %>
    <% end %>
    
    <div class="five columns" style="margin-left: 0">
    <%= f.field_container :lead_list_id do %>
        <%= f.label :lead_list_id, Spree.t(:lead_list), :class => "fullwidth" %>
        <%= f.collection_select :lead_list_id, Spree::LeadList.all.sort, :id, :name, {:include_blank => true}, :class => 'select2 fullwidth' %>
    <% end %>
    </div>

    <div class=" two columns">
      <div class="btn btn-primary" data-toggle="modal" data-target="#modalNewLeadList" style='margin-top: 31px; background: #3fcf87; border-color: #3fcf87'>
        <%=Spree.t(:new_lead_list) %>
      </div>
    </div>

    <div data-hook>
      <fieldset class="no-border-bottom no-border-top fullwidth">
        <div data-hook="add_product_name" class="fullwidth">
          <%= label_tag :change_variant_id, Spree.t(:name_or_sku_product) %>
          <%= hidden_field_tag :change_variant_id, "", :class => "variant_autocomplete fullwidth" %>
        </div>
      </fieldset>
    </div>
    <%= hidden_field_tag :lead_variant_id %>

    <div id="products-chose">
    <%= label_tag 'products-chose', Spree.t(:products_chose), :class => "fullwidth" %>
    <% if !@lead.new_record? %>
      <% @lead.products.each do |product| %>
      <% image = product.images.first %>
        <div class="product-site" id="product-site<%= product.id %>">
          <img class="image-product-previews" src="/spree/products/<%= image.id %>/mini/<%= image.attachment_file_name %>">
          <input type="hidden" id="variant_ids<%=product.id %>" value="<%= product.variants.present? ? product.variants.first.id : product.variants_including_master_ids.first %>" name="variant_ids[]">
          <i class="fa fa-trash remove-this-product" data-id="<%= product.id %>"></i>
        </div>
      <% end %>
    <% end %>
    </div>
    <div class = "clearfix"></div>

    
    <div class="control-group">
    <%= f.label :Picture, Spree.t(:Picture), class: "control-label" %>
    <div class="controls">
      <%= file_field_tag "images[]", type: :file, multiple: true %>  
    </div>
    </div>
    <div id="preview">
    </div>
    <div id="picture">
      <% @lead.pictures.each do |p| %>
        <div class="picture-site" id="picture-site<%= p.id %>">
        <%= image_tag p.image.url(:med),:class =>"picture-lead-previews"  %>
        <input type="hidden" id="Picture<%=p.id %>" value="<%= p.id %>" name="Picture[]">
        <i class="fa2x  fa  fa-trash remove-this-picture" data-id="<%= p.id %>"></i>  
      </div>
      <% end %>
      </div>
      </div>  
    <%= render :partial => "spree/admin/variants/autocomplete", :formats => :js %>
    <%= render :partial => "spree/admin/variants/autocomplete_stock", :formats => :js %>
    <%= render 'spree/admin/shared/new_lead_list_modal' %>
    </div>
    </div>
    <div class = "clearfix"></div>
    <div id="create-lead" class="align-center fullwidth" >
       <%= f.submit :id =>"click-create-lead", :class =>'fa fa-refresh button' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_leads_path, :class => ' fa fa-remove button ' %>
    </div>
  </fieldset>
<% end %>
<script>
$(document).ready(function() {
  $('#lead_phone').blur(function(e) {
      if (validatePhone('lead_phone')) {
          $('#spnPhoneStatus').html('Valid');
          $('#spnPhoneStatus').css('color', 'green');
          $("#click-create-lead").prop("disabled", false);
          $("#click-create-lead").css('background', '#3acf87');
          $('#lead_phone').css('border', '1px solid #cee1f4')
      }
      else {
          $('#spnPhoneStatus').html('Invalid');
          $('#spnPhoneStatus').css('color', 'red');
          $("#click-create-lead").prop("disabled", true);
          $("#click-create-lead").css('background', '#10131170');
          $('#lead_phone').css('border', '1px solid red');
         
      }
  });
});

function validatePhone(lead_phone) {
  var a = document.getElementById(lead_phone).value;
  var filter = /^\d{10}$/;
  if (filter.test(a)) {
      return true;
  }
  else {
      return false;
  }
}

    function onChange() {
      console.log("Changed")
       /* if ($('#lead_phone').val() != '' &&  $('#lead_name').val() != '')
        $('#create-lead input').show()
      else
        $('#create-lead input').hide() */
    }
  $(document).ready(function (){

   /* if ($('#lead_phone').val() == '' &&  $('#lead_name').val() == '')
      $('#create-lead input').hide() */


    $('#create_new_lead_list').click(function (){
        name = $('#name_lead_list').val()
        $.ajax({  
        type: "POST",
        url: "/admin/lead_lists",
        dataType: "JSON",
        data: {lead_list: { name: name } } ,
        success: function(data) {
          console.log("Create success!!!")
          $('#modalNewLeadList').modal('hide');
          $('#lead_lead_list_id').append("<option value="+ data.id + ">" + data.name + "</option>")
        }
      });
    })

    $('#change_variant_id').change(function (){
      if($('#variant_ids'+ $(this).val()).length == 0){
        preview_image_product($(this).val())
      }
      else
        console.log("Already exist")
    })
  })
    $(document).on("click", ".remove-this-product",function(e) {
    site = $(this).data('id');
    $('#product-site'+site).remove();
    console.log(site)
    console.log("Remove success!");

  })

    $(document).on("click", ".remove-this-picture",function(e) {
      site = $(this).data('id');
      $.ajax({
        type: 'DELETE',
        url:  '/pictures/' + site,
        data: {},
        dataType: 'JSON',
        contentType: 'JSON',
        success: function(res) {
          console.log("Success");
          $('#picture-site'+site).remove();
          console.log(site)
          console.log("Remove success!");
        },
        error: function(res) {
          console.log("Error");
        }
      })

  })
  function preview_image_product(id){
    $.ajax({
        type: "GET",
        url: "/admin/variants/"+ id +"/get_info",
        dataType: "JSON",
        data: {},
        success: function(data) {
          $('#products-chose').append('<div class="product-site" id="product-site' + id + '"></div>')
          $('#product-site' + id).append('<img class="image-product-previews" src="/spree/products/'+ data.id +'/mini/'+ data.attachment_file_name +'">')
          $('#product-site' + id).append('<input type="hidden" id="variant_ids'+ id + '" value="'+ id + '" name="variant_ids[]">')
          $('#product-site' + id).append('<i class="fa fa-trash remove-this-product" data-id="'+ id+ '"></i>')
          console.log('Append success!');
        },
        errors: function(data){
        console.log("Error!")
      }
      });
  }
  function previewImages() {

  var $preview = $('#preview').empty();
  if (this.files) $.each(this.files, readAndPreview);

  function readAndPreview(i, file) {
    
    if (!/\.(jpe?g|png|gif)$/i.test(file.name)){
      return alert(file.name +" is not an image");
    } // else...
    
    var reader = new FileReader();

    $(reader).on("load", function() {
     
      $preview.append($("<img/>", {src:this.result, height:100}));   
    });

    reader.readAsDataURL(file);
    
  }

}

$('#images_').on("change", previewImages);



</script>

app/views/spree/admin/leads/_list.html.erb
 <table class="index" id="listing_users" data-hook>
 <colgroup>
     <col style="width: 11%">
     <col style="width: 6%">
     <col style="width: 5%">
     <col style="width: 13%">
     <col style="width: 6%">
     <col style="width: 6%">
     <col style="width: 21%">
     <col style="width: 8%">
     <col style="width: 7%">
     <col style="width: 6%">
     <col style="width: 5%">
     <col style="width: 6%">
 </colgroup>
 <thead>
     <tr data-hook="admin_users_index_headers">
         <th><%= Spree.t(:name)%></th>
         <th><%= Spree.t(:phone)%></th>
         <th><%= Spree.t(:fb_name)%></th>
         <th><%= Spree.t(:hometown)%></th>
         <th><%= Spree.t(:major)%></th>
         <th class="text-center"><%= Spree.t(:products)%></th>
         <th><%= Spree.t(:notes) %></th>
         <th><%= Spree.t(:time) %></th>
         <th><%= Spree.t(:lead_list) %></th>
         <th><%= Spree.t(:item_total) %></th>
         <th><%= Spree.t(:total_orders) %></th>
         <th><%= Spree.t(:total_shipped) %></th>
         <th data-hook="admin_users_index_header_actions" class="actions"></th>
     </tr>
 </thead>
 <tbody>
     <% @leads.each do |lead|%>
     <tr id="<%= spree_dom_id lead %>" data-hook="admin_users_index_rows"
         class="lead_info <%= cycle('odd', 'even')%>">
         <td class="lead_name"><%= lead.name %></td>
         <td class="lead_phone"><%= lead.phone %></td>
         <td class="lead_facebook">
             <div class="lead_facebook_flex">
             <%=link_to image_tag('facebook-logo.png',:style => "width: 32px; height: 32px"),lead.fb_url.match(/^(http|https):\/\//) ? lead.fb_url : ("https://" + lead.fb_url), :target => "_blank" if lead.fb_url.present?  %>
             <% if lead.zalo.present? %>
                 <div class="zalo-info">
                     <%= image_tag 'Logo_Zalo.png',:style => "width: 29px; height: 29px; cursor: pointer"%>
                     <span class="zalo-hover"><%= lead.zalo %></span>
                 </div>
                 <script>
                     $(document).ready(()=>{
                         $(".zalo-info >img").click(()=>{
                             alert("Zalo Name: <%= lead.zalo %>");
                         })
                     });
                 </script>
             <% end %>
             </div>
         </td>
         <td class="lead_hometown">
             <% if lead.state_id.present? %>
             <%= lead.state.name %> /
             <% if lead.district_id.present? %>
             <%= lead.district.name.gsub("Thành phố ", "TP ").gsub("Thị xã ", "TX ") %>
             <% end %>
             <% end %>
         </td>
         <td class="lead_major"><%= lead.major if lead.major.present? %></td>
         <td class='user_product'>
             <%=link_to( image_tag(lead.products.last.images.first.attachment.url(:mini),:title =>"#{lead.products.last.name}", :class =>"image-product-previews"), product_path( lead.products.last)) if lead.products.last.present?%>
             <% if lead.products.present?%>
             <div class ="list_products">
             <% lead.products.each do |product| %>
                 <div class="product-site" id="product-site<%= product.id %>">
                     <%=link_to( image_tag(product.images.first.attachment.url(:mini),:title =>"#{product.name}", :class =>"image-product-previews"), product_path(product))%>
                 </div>
                 <% end %>
             </div>
             <% end %>
         </td>
         <td id='order-<%= lead.id %>' class="notes">
             <div class="show-notes">
                 <div data-hook="admin_users_index_row_actions" class="actions btn-change add-notes">
                     <%= link_to "", "##{lead.id}-notes", :class=>"fa fa-comment icon_link with-tip no-text notes"%>
                     <div style="display:none">
                         <div id="<%= lead.id %>-notes" style="width: 500px; height: 300px;">
                             <%= form_for Spree::Note.new(), :url=>admin_notes_path() do |f| %>
                             <%= f.text_field :content, :style => "width: 400px;" %>
                             <%= f.hidden_field :notable_id, :value => lead.id %>
                             <%= f.hidden_field :notable_type, :value => "Spree::Lead" %>
                             <%= f.submit Spree.t(:note) %>
                             <% end %>
                         </div>
                     </div>
                 </div>
                 <% if lead.notes.present? %>
                 <div class="note-list">
                             <%= "(#{lead.notes.last.created_at.strftime('%d/%m %H:%M')})  -  #{lead.notes.last.content}" if lead.notes.last.present? %>
                 </div>
                 <% end %>
             </div>
             <% if lead.notes.present? %>
                 <div class ="list_products_note">
                 <% lead.notes.each do |note| %>
                     <div><%= "(#{note.created_at.strftime('%d/%m %H:%M')})  -  #{note.content}" %></div>
                 <% end %>
              </div>
             <% end %>
         </td>
         <td>
             <%= time_ago_in_words(lead.created_at) %>
         </td>
         <td class="lead_list"><%= lead.lead_list.name if lead.lead_list_id.present? %></td>
         <% total_orders =lead.orders.pluck(:total).sum.round(0).to_i %>
         <td class="total_orders"><%=number_with_delimiter(total_orders,:delimiter => '.')%>&nbsp;₫</td>
         <%shipped_successfully= lead.orders.where(spree_orders: {shipment_state: "shipped_successfully"}).count.to_i %>
         <% shipped_total = lead.orders.count.to_i %>
         <td class="item_total">
                 <div class="order-shipped">
              <%= shipped_successfully %> /  <%=shipped_total  %>
             </div>
             <div class = "cleanfix"><div>
             <div class="order-choice">
                     <span>Đơn hàng: <%=shipped_total  %></span>
                     <span>Ship thành công: <%= shipped_successfully %></span>

                     <%= button_link_to (fa_icon "plus"), new_admin_order_url(:order => {:bill_address_attributes => {:firstname => lead.name, :phone => lead.phone, :state_id => lead.state_id, :district_id => lead.district_id}}, lead: lead.id), :id => 'admin_new_order', :style => "display: inline-block"  %>
                     <% if lead.orders.where.not(state: "cart").present? %>
                     <div class="btn-group">
                         <a class="button dropdown-toggle fa fa-shopping-cart" data-toggle="dropdown"
                             aria-haspopup="true" aria-expanded="false"></a>
                         <div class="dropdown-menu" style="min-width: 100px !important;">
                             <% lead.orders.where.not(state: "cart").each do |order| %>
                             <%= link_to order.number, "/admin/orders/#{order.number}/edit", :class => 'text-center', :style => "display: block; border-bottom: none", target: "_blank" %>
                             <% end %>
                         </div>
                     </div>
                     <% end %>
             </div>
         </td>
         <% total_shipped =lead.orders.where(spree_orders: {shipment_state: "shipped_successfully"}).pluck(:total).sum.round(0).to_i %>
         <td class="total_orders"><%=number_with_delimiter(total_shipped,:delimiter => '.')%>&nbsp;₫</td>
         
         <td data-hook="admin_users_index_row_actions" class="actions btn-change">
             <%#= link_to_user user, :no_text => true %>
             <%= link_to_edit lead, :no_text => true, :class => 'edit' %>
             
         </td>
     </tr>
     <% end %>
 </tbody>
</table>

    <%= paginate @leads %>

app/views/spree/admin/leads/edit.html.erb
<%= render "form" %>

app/views/spree/admin/leads/index.js.erb
    $("#list_lead").html("<%= escape_javascript(render partial: 'list', locals: { leads: @leads } ) %>"); 

app/views/spree/admin/leads/new.html.erb
<%= render "form" %>